---
- name: add prometheus datasource
  grafana_datasource:
    name: "prometheus-local"
    grafana_url: "http://127.0.0.1:3000"
    grafana_user: "admin"
    grafana_password: "uthaya123"
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://localhost:9090"
  changed_when: false
  when: ansible_hostname == 'uthaya-Latitude-5400'

- name: add prometheus datasource
  grafana_datasource:
    name: "prometheus-local"
    grafana_url: "http://172.16.1.64:3000"
    grafana_user: "admin"
    grafana_password: "uthaya123"
    org_id: "1"
    ds_type: "prometheus"
    ds_url: "http://172.16.1.64:9090"
  changed_when: false
  when: ansible_hostname == 'uthaya123'

- name: install node exporter dashboard
  get_url:
    url: https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
    dest: /var/lib/grafana/node-exporter.json
    mode: '0755'
  when: ansible_hostname == 'uthaya-Latitude-5400'

- name: install node exporter dashboard
  get_url:
    url: https://raw.githubusercontent.com/rfrail3/grafana-dashboards/master/prometheus/node-exporter-full.json
    dest: /var/lib/grafana/node-exporter.json
    mode: '0755'
  when: ansible_hostname == 'turbo'

- name: activate dashboard for node interview
  template:
    src: dashboard-node-exporter.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-node-exporter.yml
    mode: 0755
  notify: restart_grafana
  when: ansible_hostname == 'uthaya-Latitude-5400'

- name: activate dashboard for node interview
  template:
    src: dashboard-node-exporter.yml.j2
    dest: /etc/grafana/provisioning/dashboards/dashboard-node-exporter.yml
    mode: 0755
  notify: restart_grafana
  when: ansible_hostname == 'turbo'
